services:
  app:
    container_name: jira
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      - db
      - nginx
    networks:
      - jira-network

  db:
    image: postgres:latest
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    env_file:
      - path: ./secure.env
        required: true
    environment:
      - POSTGRES_USER=${DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${DATASOURCE_PASSWORD}
      - POSTGRES_DB=jira
    ports:
      - "5432:5432"
    networks:
      - jira-network

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/nginx.conf
    networks:
      - jira-network

networks:
  jira-network:
    driver: bridge