spring:
  datasource:
    username: jira #TODO CRED_MARKER
    password: JiraRush #TODO CRED_MARKER

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 3d0d8738e65881fff266 #TODO CRED_MARKER
            client-secret: 0f97031ce6178b7dfb67a6af587f37e222a16120 #TODO CRED_MARKER
          google:
            client-id: 329113642700-f8if6pu68j2repq3ef6umd5jgiliup60.apps.googleusercontent.com #TODO CRED_MARKER
            client-secret: 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 #TODO CRED_MARKER
          gitlab:
            client-id: b8520a3266089063c0d8261cce36971defa513f5ffd9f9b7a3d16728fc83a494 #TODO CRED_MARKER
            client-secret: e72c65320cf9d6495984a37b0f9cc03ec46be0bb6f071feaebbfe75168117004 #TODO CRED_MARKER

  mail:
    host: smtp.gmail.com #TODO CRED_MARKER
    username: jira4jr@gmail.com #TODO CRED_MARKER
    password: zdfzsrqvgimldzyj #TODO CRED_MARKER
    port: 587 #TODO CRED_MARKER